### PR TITLE
Add osx_arm64

### PR DESCRIPTION
**Pull request by mottelet**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by zklaus** [comment]
I don't think this PR does what you want it to do, namely it doesn't add a build for arm64. Have a look at [this blog post](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock) and consider adding this feedstock to the list at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

**Comment by mottelet** [comment]
> I don't think this PR does what you want it to do, namely it doesn't add a build for arm64. Have a look at [this blog post](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock) and consider adding this feedstock to the list at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

I added the packages names (subversion, apache-ant, ocaml, ocaml-num) in this migration file, but it does not seem to have triggered their build so far.

**Comment by zklaus** [comment]
Great, @mottelet, thanks for doing that! You can follow the progress at https://conda-forge.org/status/#armosxaddition. The interface is a little bit clunky, but you can click on the magenta buttons to get a list of the respective packages. There you can see that `ocaml` is now in PR (see conda-forge/ocaml-feedstock#35), whereas the others are "awaiting-parents", i.e. there are dependencies in the queue that need to be migrated first before that package can be tackled.

**Comment by zklaus** [comment]
If you open [this svg](https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/armosxaddition.svg) you can search for subversion and see exactly which packages are needed.

**Comment by mottelet** [comment]
> If you open [this svg](https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/armosxaddition.svg) you can search for subversion and see exactly which packages are needed.

In the raw log I saw a problem I already encoutered in the configure script
```
2023-02-02T20:42:29.0783080Z Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
```
In my personal projects I had to explicitely replace `arm64` by `aarch64` and add the switches:
```
--build=aarch64-apple-darwin20.0.0 --host=aarch64-apple-darwin20.0.0
```

**Comment by zklaus** [comment]
The dependencies for subversion that still need to be migrated are as follows:
```mermaid
graph TD;
  libksba-->ntbtls;
  libksba-->gnupg;
  ntbtls-->gnupg;
  npth-->gnupg;
  gnupg-->subversion;
```

Currently, libksba has a PR (conda-forge/libksba-feedstock#7) and npth (conda-forge/npth-feedstock#4). Once they are done, ntbtls will be tackled and then GnuPG. That will open the way for subversion.

**Comment by mottelet** [comment]
For ocaml this is even worse
```
2023-02-06T15:34:29.1054000Z + MINIFORGE_FILE=Mambaforge-MacOSX-x86_64.sh
2023-02-06T15:34:29.1083430Z + curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh
```
i.e. the build process installs a x86_64 miniforge instead of a osx_arm64.

**Comment by zklaus** [comment]
Sorry, which build are you referring to? Shall we tackle one after the other and discuss things in the respective PRs? In that case, first libksba or first npth?

**Comment by mottelet** [comment]
> Sorry, which build are you referring to? Shall we tackle one after the other and discuss things in the respective PRs? In that case, first libksba or first npth?

```
2023-02-02T20:42:54.4712930Z Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
```
and 
```
2023-02-02T20:35:30.7470840Z + MINIFORGE_FILE=Mambaforge-MacOSX-x86_64.sh
2023-02-02T20:35:30.7541130Z + curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh
```
is for `npth`

**Comment by zklaus** [comment]
We'll have to follow the guidance at https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock which means first adding `gnuconfig` and `make` to the deps of libskba.

**Comment by zklaus** [comment]
I've started this project in conda-forge/libksba-feedstock#9.

**Pull request closed without merging**
